<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-F09LMPV" failures="1" tests="1" name="OmayoTest" time="14.348" errors="0" timestamp="2021-04-26T15:41:38 IST">
  <testcase classname="test.OmayoTest" name="launchOmayo" time="13.388">
    <failure type="java.lang.AssertionError" message="expected [omayo (QAFox.com)1123] but found [omayo (QAFox.com)]">
      <![CDATA[java.lang.AssertionError: expected [omayo (QAFox.com)1123] but found [omayo (QAFox.com)]
at test.OmayoTest.launchOmayo(OmayoTest.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- launchOmayo -->
</testsuite> <!-- OmayoTest -->
